apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 1password-connect
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: 1password
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: connect
    repoURL: https://1password.github.io/connect-helm-charts
    targetRevision: 1.15.0
    helm:
      paramaters:
      - name: connect.credentials_base64
        valueFrom:
          secretKeyRef:
            name: op-credentials
            key: 1password-credentials.json
      valuesObject:
        operator:
          create: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 15s
        factor: 2
        maxDuration: 5m
