apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: seaweedfs
  namespace: argocd
spec:
  destination:
    namespace: seaweedfs
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: seaweedfs-csi-driver
    repoURL: https://seaweedfs.github.io/seaweedfs-csi-driver/helm
    targetRevision: 4.6.8
    helm:
      valuesObject:
        seaweedfsFiler: "rasomniac:8888"
        node:
          affinity: &affinity
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: NotIn
                    values:
                    - rasomniac

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - ServerSideApply=true
    - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 15s
        factor: 2
        maxDuration: 5m
