apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tailscale-k8s-operator
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: tailscale
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: tailscale-operator
    repoURL: "https://pkgs.tailscale.com/helmcharts"
    targetRevision: "1.84.3"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 15s
        factor: 2
        maxDuration: 5m
