apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trivy-operator
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: trivy-system
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: trivy-operator
    repoURL: https://aquasecurity.github.io/helm-charts/
    targetRevision: 0.24.1
    helm:
      valuesObject: 
        serviceMonitor:
          # enabled determines whether a serviceMonitor should be deployed
          enabled: true
        trivy:
          ignoreUnfixed: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

