apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tts-server
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: tts-server
    server: https://kubernetes.default.svc
  project: default
  source:
    path: tts-server
    repoURL: https://github.com/sierra-alpha/agrocd-auto-deploy-apps
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 15s
        factor: 2
        maxDuration: 5m
