apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-storage-pv
  labels:
    type: local
spec:
  storageClassName: local-path
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  local:
    path: /mnt/nfs/ssc/storage/nextcloud
  nodeAffinity:
    - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
            - rasomniac
            - rampid2
            - airsomniac1
            - airsomniac2
            - prosomniac
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-storage-pvc
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
