---
#
# Passwords
#
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: nextcloud-postgresql-password
spec:
  itemPath:
    "vaults/K8s Service Account/items/nextcloud-postgresql-password"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: nextcloud-redis-password
spec:
  itemPath:
    "vaults/K8s Service Account/items/nextcloud-redis-password"
