# Data Volumes
#
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-storage-pv
  namespace: nextcloud
spec:
  capacity:
    storage: 2Ti
  accessModes:
    - ReadWriteMany
  nfs:
    server: rasomniac.sierraalpha.co.nz
    path: /srv/nfs/ssc
  mountOptions:
    - nfsvers=4.2
    - rw
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-storage-pvc
  namespace: nextcloud
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 2Ti
  volumeName: nextcloud-storage-pv
#
# Passwords
#
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: nextcloud-postgresql-password
spec:
  itemPath:
    "vaults/K8s Service Account/items/nextcloud-postgresql-password"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: nextcloud-redis-password
spec:
  itemPath:
    "vaults/K8s Service Account/items/nextcloud-redis-password"
