---
#
# Config Volumes
#
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-config-pv
  namespace: nextcloud
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 8Gi
  csi:
    driver: seaweedfs-csi-driver
    volumeHandle: nextcloud-config
    volumeAttributes:
      collection: default
      replication: "002"
      path: /buckets/k8s-data/nextcloud-config
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-config-pvc
  namespace: nextcloud
spec:
  storageClassName: ""
  volumeName: nextcloud-config-pv
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 8Gi
---
#
# Data Volumes
#
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-data-pv
  namespace: nextcloud
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 2Ti
  csi:
    driver: seaweedfs-csi-driver
    volumeHandle: nextcloud-data
    volumeAttributes:
      collection: default
      replication: "001"
      path: /buckets/k8s-data/nextcloud-data
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-data-pvc
  namespace: nextcloud
spec:
  storageClassName: ""
  volumeName: nextcloud-data-pv
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2ti
---
#
# Database Volumes
#
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-db-pv
  namespace: nextcloud
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 8Gi
  csi:
    driver: seaweedfs-csi-driver
    volumeHandle: nextcloud-db
    volumeAttributes:
      collection: default
      replication: "002"
      path: /buckets/k8s-data/nextcloud-db
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-db-pvc
  namespace: nextcloud
spec:
  storageClassName: ""
  volumeName: nextcloud-db-pv
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 8Gi
---
#
# Passwords
#
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: nextcloud-postgresql-password
spec:
  itemPath:
    "vaults/K8s Service Account/items/nextcloud-postgresql-password"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: nextcloud-redis-password
spec:
  itemPath:
    "vaults/K8s Service Account/items/nextcloud-redis-password"
