apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-storage-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: rasomniac.sierraalpha.co.nz
    path: /srv/nfs/ssc/nextcloud
  mountOptions:
    - nfsvers=4.2
    - rw
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-storage-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 8Gi
  volumeName: nextcloud-nfs
