---
#
# Passwords
#
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: machines-google-password
spec:
  itemPath:
    "vaults/K8s Service Account/items/machines-google"
---
#
# Config Map
#
# Another good US speaker:
# speaker_id: Torcull Diarmuid
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ttser-configmap
data:
  config.yaml: |
    gmail_email: machines.shaun.t.alexander@gmail.com
    output_location: /podcasts
    processed_label: Processed
    tts_url:
      - https://tts-server.app.sierraalpha.co.nz/api/tts

    newsletters:
      - podcast_title: Money Stuff Newsletter TTS
        language_id: en
        senders:
          - Matt Levine
          - Shaun Alexander
        speaker_id: Damien Black
        subject_terms:
          - "Money Stuff:"
          - "Money_Stuff:"

      - podcast_title: Points of Return Newsletter TTS
        language_id: en
        senders:
          - John Authers
        speaker_id: Ludvig Milivoj

---
#
# Audiobook Volumes
#
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: audiobookshelf-audiobooks-pv
  namespace: audiobookshelf
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 50Gi
  csi:
    driver: seaweedfs-csi-driver
    volumeHandle: audiobookshelf-audiobooks
    volumeAttributes:
      collection: default
      replication: "001"
      path: /buckets/k8s-data/audiobookshelf-audiobooks
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audiobookshelf-audiobooks-pvc
  namespace: audiobookshelf
spec:
  storageClassName: ""
  volumeName: audiobookshelf-audiobooks-pv
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
---
#
# Podcast Volumes
#
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: audiobookshelf-podcasts-pv
  namespace: audiobookshelf
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 50Gi
  csi:
    driver: seaweedfs-csi-driver
    volumeHandle: audiobookshelf-podcasts
    volumeAttributes:
      collection: default
      replication: "001"
      path: /buckets/k8s-data/audiobookshelf-podcasts
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audiobookshelf-podcasts-pvc
  namespace: audiobookshelf
spec:
  storageClassName: ""
  volumeName: audiobookshelf-podcasts-pv
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
---
#
# Config Volumes
#
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: audiobookshelf-config-pv
  namespace: audiobookshelf
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 5Gi
  csi:
    driver: seaweedfs-csi-driver
    volumeHandle: audiobookshelf-config
    volumeAttributes:
      collection: default
      replication: "001"
      path: /buckets/k8s-data/audiobookshelf-config
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audiobookshelf-config-pvc
  namespace: audiobookshelf
spec:
  storageClassName: ""
  volumeName: audiobookshelf-config-pv
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
#
# Metadata Volumes
#
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: audiobookshelf-metadata-pv
  namespace: audiobookshelf
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 15Gi
  csi:
    driver: seaweedfs-csi-driver
    volumeHandle: audiobookshelf-metadata
    volumeAttributes:
      collection: default
      replication: "001"
      path: /buckets/k8s-data/audiobookshelf-metadata
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audiobookshelf-metadata-pvc
  namespace: audiobookshelf
spec:
  storageClassName: ""
  volumeName: audiobookshelf-metadata-pv
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 15Gi
---
#
# Ingress
#
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    traefik.ingress.kubernetes.io/router.middlewares:
      traefik-redirecthttps@kubernetescrd
  labels:
    app: audiobookshelf
  name: audiobookshelf
  namespace: audiobookshelf
spec:
  ingressClassName: traefik
  rules:
  - host: audiobookshelf.app.sierraalpha.co.nz
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: audiobookshelf
            port:
              number: 80
  tls:
  - hosts:
    - audiobookshelf.app.sierraalpha.co.nz
    secretName: audiobookshelf-app-sierraalpha-tls
---
apiVersion: v1
kind: Service
metadata:
  name: audiobookshelf
  namespace: audiobookshelf
spec:
  ports:
    - port: 80
      protocol: TCP
  selector:
    app: audiobookshelf
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: audiobookshelf
  namespace: audiobookshelf
spec:
  selector:
    matchLabels:
      app: audiobookshelf
  replicas: 1
  template:
    metadata:
      labels:
        app: audiobookshelf
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: NotIn
                values:
                - rasomniac
                - obsidian
      containers:
        - name: audiobookshelf
          image: ghcr.io/advplyr/audiobookshelf
          ports:
          - containerPort: 80
          volumeMounts:
            - name: audiobookshelf-audiobooks-volume
              mountPath: /audiobooks
            - name: audiobookshelf-config-volume
              mountPath: /config
            - name: audiobookshelf-metadata-volume
              mountPath: /metadata
            - name: audiobookshelf-podcasts-volume
              mountPath: /podcasts
      volumes:
        - name: audiobookshelf-audiobooks-volume
          persistentVolumeClaim:
            claimName: audiobookshelf-audiobooks-pvc
        - name: audiobookshelf-config-volume
          persistentVolumeClaim:
            claimName: audiobookshelf-config-pvc
        - name: audiobookshelf-metadata-volume
          persistentVolumeClaim:
            claimName: audiobookshelf-metadata-pvc
        - name: audiobookshelf-podcasts-volume
          persistentVolumeClaim:
            claimName: audiobookshelf-podcasts-pvc
---
#
# ttser
#
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: ttser
  namespace: audiobookshelf
spec:
  schedule: "*/30 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: kubernetes.io/hostname
                        operator: NotIn
                        values:
                          - rasomniac
                          - obsidian
          containers:
            - name: ttser
              image: ghcr.io/sierra-alpha/voicemail
              env:
                - name: GMAIL_APP_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: machines-google-password
                      key: app-password
              volumeMounts:
                - name: ttser-config
                  mountPath: /config.yaml
                  subPath: config.yaml
                - name: audiobookshelf-podcasts-volume
                  mountPath: /podcasts
          restartPolicy: OnFailure
          volumes:
            - name: ttser-config
              configMap:
                name: ttser-configmap
            - name: audiobookshelf-podcasts-volume
              persistentVolumeClaim:
                claimName: audiobookshelf-podcasts-pvc
