apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    traefik.ingress.kubernetes.io/router.middlewares:
      traefik-redirecthttps@kubernetescrd
  labels:
    app: haos
  name: haos
  namespace: haos
spec:
  rules:
  - host: haos.app.sierraalpha.co.nz
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: haos
            port:
              number: 80
  tls:
  - hosts:
    - haos.app.sierraalpha.co.nz
    secretName: haos-app-sierraalpha-tls
---
apiVersion: v1
kind: Service
metadata:
  name: haos
  namespace: haos
spec:
  externalName: homeassistant.sierraalpha.co.nz
  ports:
    - port: 80
      targetPort: 8123
      protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: haos-endpoints
  namespace: haos
subsets:
  - addresses:
      - ip: 192.168.1.100 # The external IP address
    ports:
      - port: 8123
