apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    traefik.ingress.kubernetes.io/router.middlewares:
      traefik-redirecthttps@kubernetescrd
  labels:
    app: haos
  name: haos
  namespace: haos
spec:
  rules:
  - host: haos.app.sierraalpha.co.nz
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: haos
            port:
              number: 80
  tls:
  - hosts:
    - haos.app.sierraalpha.co.nz
    secretName: haos-app-sierraalpha-tls
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app: haos
  name: haos-tailscale
  namespace: haos
spec:
  defaultBackend:
    service:
      name: haos
      port:
        number: 80
  ingressClassName: tailscale
  tls:
    - hosts:
        - haos
---
apiVersion: v1
kind: Service
metadata:
  name: haos
spec:
  type: ExternalName
  externalName: homeassistant.sierraalpha.co.nz
  ports:
    - port: 80
      targetPort: 8123
