apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    traefik.ingress.kubernetes.io/router.middlewares:
      traefik-redirecthttps@kubernetescrd
  labels:
    app: nextcloud
  name: nextcloud
  namespace: nextcloud
spec:
  ingressClassName: traefik
  rules:
  - host: nextcloud.app.sierraalpha.co.nz
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: nextcloud
            port:
              number: 80
  tls:
  - hosts:
    - nextcloud.app.sierraalpha.co.nz
    secretName: nextcloud-app-sierraalpha-tls
---
apiVersion: v1
kind: Service
metadata:
  name: nextcloud
spec:
  ports:
    - port: 80
      protocol: TCP
  selector:
    app: nextcloud
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud
spec:
  selector:
    matchLabels:
      app: nextcloud
  replicas: 1
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      containers:
      - name: nextcloud
        image: nextcloud/all-in-one
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: nextcloud-data
          mountPath: /usr/share/nginx/html
      volumes:
      - name: hello-world-volume
        configMap:
          name: hello-world-configmap

# Data Volumes
#
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-storage-pv
  namespace: nextcloud
spec:
  capacity:
    storage: 2Ti
  accessModes:
    - ReadWriteMany
  nfs:
    server: rasomniac.sierraalpha.co.nz
    path: /srv/nfs/ssc
  mountOptions:
    - nfsvers=4.2
    - rw
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-storage-pvc
  namespace: nextcloud
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 2Ti
  volumeName: nextcloud-storage-pv
#
# Passwords
#
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: nextcloud-postgresql-password
spec:
  itemPath:
    "vaults/K8s Service Account/items/nextcloud-postgresql-password"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: nextcloud-redis-password
spec:
  itemPath:
    "vaults/K8s Service Account/items/nextcloud-redis-password"


# Previous go at using a helm chart this was in the app of apps

# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   finalizers:
#   - resources-finalizer.argocd.argoproj.io
#   name: nextcloud
#   namespace: argocd
# spec:
#   destination:
#     namespace: nextcloud
#     server: https://kubernetes.default.svc
#   project: default
#   source:
#     chart: nextcloud
#     repoURL: https://nextcloud.github.io/helm
#     targetRevision: 4.6.6
#     helm:
#       valuesObject:
#         nextcloud:
#           host: nextcloud.app.sierraalpha.co.nz
#         ingress:
#           enabled: true
#           className: traefik
#           annotations:
#             cert-manager.io/cluster-issuer: letsencrypt-production
#             kubernetes.io/ingress.class: traefik
#             traefik.ingress.kubernetes.io/router.middlewares:
#               traefik-redirecthttps@kubernetescrd
#           tls:
#           - secretName: nextcloud-tls
#             hosts:
#             - nextcloud.app.sierraalpha.co.nz
#         phpClientHttpsFix:
#           enabled: true
#         cronjob:
#           enabled: true
#         persistence:
#           enabled: false
#           nextcloudData:
#             enabled: true
#             existingClaim: nextcloud-storage-pvc
#             accessMode: ReadWriteMany
#             size: 2Ti

#         redis:
#           enabled: true
#           auth:
#             enabled: true
#             existingSecret: nextcloud-redis-password
#             existingSecretPasswordKey: password

#         internalDatabase:
#           enabled: false
#         externalDatabase:
#           enabled: true
#           type: postgresql
#           existingSecret:
#             enabled: true
#             secretName: nextcloud-postgresql-password
#             usernameKey: username
#             passwordKey: password
#         postgresql:
#           enabled: true
#           global:
#             postgresql:
#               auth:
#                 existingSecret: nextcloud-postgresql-password
#                 secretKeys:
#                   adminPasswordKey: password
#                   userPasswordKey: password
#                   replicationPasswordKey: password
#           primary:
#             persistence:
#               enabled: true

#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true
#     syncOptions:
#     - ServerSideApply=true
#     - CreateNamespace=true
#     retry:
#       limit: 5
#       backoff:
#         duration: 15s
#         factor: 2
#         maxDuration: 5m
