apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: cloudflare-dns-token-sierraalpha.co.nz
  namespace: cert-manager
spec:
  itemPath:
    "vaults/K8s Service Account/items/cloudflare-edit-zone-dns-sierraalpha.co.nz"
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: shaun@sierraalpha.co.nz
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
    - dns01:
        cloudflare:
          apiTokenSecretRef:
            name: cloudflare-dns-token-sierraalpha.co.nz
            key: api-token
        ingress:
          class: traefik
