kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: acme-copy-token-role
subjects:
- kind: ServiceAccount
  name: acme-copy-token-role
  namespace: cert-manager
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: acme-copy-token-role
  namespace: cert-manager
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: acme-token-copy-cron
  namespace: cert-manager
spec:
  schedule: "*/20 8-19 * * 1-5"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: well
        spec:
          containers:
            - name: acme-token-copy-job
              serviceAccountName: acme-copy-token-role
              image: acme-token-s3-upload
                imagePullPolicy: IfNotPresent
              restartPolicy: OnFailure

