kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: acme-copy-token-role
subjects:
- kind: ServiceAccount
  name: acme-copy-token-role
  namespace: cert-manager
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: acme-copy-token-role
  namespace: cert-manager
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: token-files-cm
data:
  make-token-files.sh: |
    kubectl get challenges \
    -o jsonpath='{.items[].spec.token} {.items[].spec.key}' \
      | while read -r token-and-key; do
          echo "$token-and-key[1]" > "$UPLOAD_LOCATION/$token-and-key[0]"
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: acme-token-cloud-copy-cron
  namespace: cert-manager
spec:
  schedule: "* * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: well-known-acme-token-cloud-copy
        spec:
          serviceAccountName: acme-copy-token-role
          restartPolicy: Never
          containers:
          - name: acme-token-cloud-copy-job
            image: rclone/rclone
            volumeMounts:
            - name: data-dir
              mountPath: /data
          initContainers:
          - name: token-file-writer
            image: bitnami/kubectl
            command: ["/usr/bin/bash"]
            args:  ["--", "/scripts/make-token-files.sh"]
            env:
            - name: UPLOAD_LOCATION
              value: /data
            volumeMounts:
            - name: data-dir
              mountPath: /data
            - name: script-dir
              mountPath: /scripts
          volumes:
          - name: data-dir
            emptyDir: {}
          - name: script-dir
            configMap:
              name: token-files-cm
---
apiVersion: batch/v1
kind: CronJob
metadata:
 name: acme-token-cloud-cleanup-cron
 namespace: cert-manager
spec:
 schedule: "0 0 * * 1"
 concurrencyPolicy: Forbid
 jobTemplate:
   spec:
     template:
       metadata:
         labels:
           app: well
       spec:
         restartPolicy: OnFailure
         containers:
         - name: acme-token-cleanup-job
           image: rclone/rclone
