apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    traefik.ingress.kubernetes.io/router.middlewares:
      traefik-redirecthttps@kubernetescrd
  labels:
    app: tts-server
  name: tts-server
  namespace: tts-server
spec:
  rules:
  - host: xttsss.app.sierraalpha.co.nz
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: tts-server
            port:
              number: 80
  tls:
  - hosts:
    - xttsss.app.sierraalpha.co.nz
    secretName: xttsss-app-sierraalpha-tls
---
apiVersion: v1
kind: Service
metadata:
  name: tts-server
  namespace: tts-server
spec:
  ports:
    - port: 80
      protocol: TCP
  selector:
    app: tts-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tts-server
  namespace: tts-server
spec:
  selector:
    matchLabels:
      app: tts-server
  replicas: 1
  template:
    metadata:
      labels:
        app: tts-server
    spec:
      nodeName: prosomniac
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: NotIn
                values:
                - rasomniac
      containers:
      - name: tts-server
        image: ghcr.io/coqui-ai/tts-cpu
        command:
        - '/bin/bash'
        args:
        - 'python3 TTS/server/server.py'
        ports:
        - containerPort: 5002
