apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: operator-oauth
  namespace: tailscale
spec:
  itemPath:
    "vaults/K8s Service Account/items/tailscale-oauth-client-k8s-operator"
